import React,{useEffect,useState}from'react';
import{Link,NavLink,useLocation,useNavigate,useParams}from'react-router-dom';
import{COURSES}from'./data/courses.js';
import'./styles.css';

const KEY='tamp_v2';
const store=()=>JSON.parse(localStorage.getItem(KEY)||'{"users":{},"s":null,"p":{},"n":[],"last":"py"}');
const save=d=>localStorage.setItem(KEY,JSON.stringify(d));
const me=()=>{const d=store();return d.s&&d.users[d.s]};
const lessons=c=>c?.modules?.flatMap(m=>m.l||[])||[];
const pct=c=>{const d=store(),ls=lessons(c);return ls.length?Math.round(ls.filter(x=>d.p[`${c.id}:${x.id}`]?.done).length/ls.length*100):0};

const Icon=({n})=><svg className="i" viewBox="0 0 24 24"><path d={{home:'M3 11l9-8 9 8v9H3z',book:'M4 4h12a4 4 0 014 4v12H8a4 4 0 01-4-4z',cap:'M12 3l10 5-10 5L2 8z',user:'M12 8a4 4 0 100-8 4 4 0 000 8zM4 21c0-4 4-6 8-6s8 2 8 6',bell:'M6 8a6 6 0 0112 0c0 7 3 8 3 8H3s3-1 3-8',moon:'M20 14A8 8 0 019.5 4 8 8 0 1020 14z',back:'M15 5l-7 7 7 7',check:'M5 12l5 5L20 7',arrow:'M5 12h14M13 6l6 6-6 6'}[n]}/></svg>;

function Layout({children}){
 const u=me(),[dark,setDark]=useState(localStorage.getItem('th')==='dark');
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('th',dark?'dark':'light')},[dark]);
 const links=u?[['/','Home','home'],['/learn','Learn','cap'],['/courses','Courses','book'],['/profile','Me','user']]:[['/','Home','home'],['/courses','Courses','book'],['/verify','Verify','check'],['/login','Sign in','user']];
 return <div className="app-shell"><header className="top"><Link className="logo" to="/">TAMP</Link><div className="top-actions">{u&&<Link className="ib" to="/notifications"><Icon n="bell"/></Link>}<button className="ib" onClick={()=>setDark(!dark)}><Icon n="moon"/></button></div></header><main>{children}</main><nav className="tabs">{links.map(([to,t,n])=><NavLink key={to} to={to} end={to==='/' } className={({isActive})=>isActive?'on':''}><Icon n={n}/>{t}</NavLink>)}</nav></div>
}

const Card=({c})=><Link className="cc" style={{'--c':c.color||'#4f46e5'}} to={`/courses/${c.id}`}><span className="t">{c.tag||'Course'}</span><h3>{c.title}</h3><p className="mu">{c.desc||c.learn?.[0]}</p><div className="bar"><i style={{width:pct(c)+'%'}}/></div><small className="mu">{pct(c)}% complete · {c.hours||0} hours</small></Link>;

function Home(){const u=me();return <><section className="hero"><p className="mu">Technical campus</p><h1>{u?`Welcome back, ${u.name||'learner'}.`:'Learn to build what the future runs on.'}</h1><p className="mu">Structured courses, tracked progress, assessments and practical projects.</p><Link className="btn" to={u?'/learn':'/signup'}>{u?'Continue learning':'Start learning'}</Link></section><section className="wrap"><div className="section-head"><h2>Courses</h2><Link to="/courses">View all</Link></div>{COURSES.slice(0,4).map(c=><Card c={c} key={c.id}/>)}</section></>}

function Courses(){const[q,setQ]=useState('');const list=COURSES.filter(c=>(c.title+' '+(c.tag||'')).toLowerCase().includes(q.toLowerCase()));return <section className="sec"><div className="hero inner"><p className="mu">TAMP curriculum</p><h1>Courses</h1><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search courses"/></div>{list.map(c=><Card c={c} key={c.id}/>)}</section>}

function Course(){const{id}=useParams(),c=COURSES.find(x=>x.id===id),nav=useNavigate(),u=me();if(!c)return <NotFound/>;const start=lessons(c)[0],en=u?.courses?.includes(c.id);
 const enroll=()=>{if(!u)return nav('/login');const d=store();d.users[d.s].courses=[...(d.users[d.s].courses||[]),...(d.users[d.s].courses||[]).includes(c.id)?[]:[c.id]];d.last=c.id;save(d);nav(`/lesson/${c.id}/${start?.id}`)};
 return <section className="sec"><button className="link-back" onClick={()=>nav(-1)}><Icon n="back"/> Back</button><article className="card"><span className="pill" style={{'--c':c.color}}>{c.tag||'Course'}</span><h1>{c.title}</h1><p className="mu">{c.desc}</p><div className="bar"><i style={{width:pct(c)+'%'}}/></div><p className="mu">{pct(c)}% complete · {c.hours||0} hours</p>{en?<Link className="btn" to={`/learn/${c.id}`}>Continue</Link>:<button className="btn" onClick={enroll}>{u?'Enroll & start':'Sign in to start'}</button>}</article><div className="card"><h2>What you'll learn</h2><ul>{(c.learn||[]).map(x=><li key={x}>{x}</li>)}</ul></div><h2>Curriculum</h2>{(c.modules||[]).map(m=><details className="nv" key={m.t} open><summary>{m.t}</summary>{(m.l||[]).map(l=><Link key={l.id} to={`/lesson/${c.id}/${l.id}`}><span>{l.id} · {l.t}</span><span className="mu">{l.min||10}m</span></Link>)}</details>)}</section>
}

function Learn(){const{id}=useParams(),d=store(),c=COURSES.find(x=>x.id===id)||COURSES.find(x=>x.id===d.last)||COURSES.find(x=>me()?.courses?.includes(x.id))||COURSES[0],next=lessons(c).find(l=>!d.p[`${c.id}:${l.id}`]?.done)||lessons(c)[0];return <section className="sec"><div className="hero inner"><p className="mu">Your learning</p><h1>{c.title}</h1><div className="bar"><i style={{width:pct(c)+'%'}}/></div></div><div className="card"><p className="mu">Next lesson</p><h2>{next?.t||'Course complete'}</h2>{next&&<Link className="btn" to={`/lesson/${c.id}/${next.id}`}>Continue <Icon n="arrow"/></Link>}</div></section>}

function Lesson(){const{courseId,lessonId}=useParams(),c=COURSES.find(x=>x.id===courseId),l=lessons(c).find(x=>x.id===lessonId),nav=useNavigate(),[,rerender]=useState(0);if(!c||!l)return <NotFound/>;const d=store(),done=!!d.p[`${c.id}:${l.id}`]?.done,next=lessons(c)[lessons(c).findIndex(x=>x.id===l.id)+1];const complete=()=>{const s=store();s.p[`${c.id}:${l.id}`]={done:true,at:Date.now()};s.last=c.id;save(s);rerender(x=>x+1)};return <section className="sec"><button className="link-back" onClick={()=>nav(`/courses/${c.id}`)}><Icon n="back"/> {c.title}</button><article><p className="mu">{l.k||'Lesson'} · {l.min||10} min</p><h1>{l.t}</h1>{l.obj&&<div className="req"><b>Objectives</b>{l.obj.map(x=><p key={x}><Icon n="check"/>{x}</p>)}</div>}<div className="lesson-body" dangerouslySetInnerHTML={{__html:l.b||'<p>Complete this lesson and continue.</p>'}}/>{l.tasks&&<div className="card"><h3>Practice</h3><ul>{l.tasks.map(x=><li key={x}>{x}</li>)}</ul></div>}<button className="btn" onClick={complete}>{done?'Completed ✓':'Mark lesson complete'}</button>{next&&<button className="btn o" onClick={()=>nav(`/lesson/${c.id}/${next.id}`)}>Next lesson <Icon n="arrow"/></button>}</article></section>}

function Auth({signup=false}){const[f,setF]=useState({name:'',email:'',pw:'',pw2:''}),[e,setE]=useState(''),nav=useNavigate();const submit=ev=>{ev.preventDefault();const d=store(),email=f.email.trim().toLowerCase();if(!email||!email.includes('@'))return setE('Enter a valid email address.');if(signup){if(f.pw.length<8)return setE('Password must be at least 8 characters.');if(f.pw!==f.pw2)return setE('Passwords do not match.');if(d.users[email])return setE('Account already exists.');d.users[email]={name:f.name.trim()||'Learner',email,pw:f.pw,courses:[]}}else if(!d.users[email]||d.users[email].pw!==f.pw)return setE('Email or password is incorrect.');d.s=email;save(d);nav('/')};return <section className="auth-wrap"><div className="aut"><div className="brand">TAMP</div><p className="tag">Learn to build what the future runs on.</p></div><form className="card auth" onSubmit={submit}><h2>{signup?'Create your account':'Sign in'}</h2>{signup&&<><label>Name</label><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></>}<label>Email</label><input type="email" required value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><label>Password</label><input type="password" required value={f.pw} onChange={e=>setF({...f,pw:e.target.value})}/>{signup&&<><label>Confirm password</label><input type="password" required value={f.pw2} onChange={e=>setF({...f,pw2:e.target.value})}/></>}<p className="err">{e}</p><button className="btn">{signup?'Create account':'Sign in'}</button><p className="mu">{signup?<Link to="/login">Already have an account?</Link>:<>New here? <Link to="/signup">Create an account</Link></>}</p></form></section>}

function Profile(){const u=me(),nav=useNavigate();if(!u)return <NotFound/>;return <section className="sec"><div className="card pc"><div className="av">{u.name?.[0]?.toUpperCase()||'L'}</div><h2>{u.name}</h2><p className="mu">{u.email}</p><div className="st"><div><b>{u.courses?.length||0}</b><span>Courses</span></div><div><b>{Object.values(store().p).filter(x=>x.done).length}</b><span>Lessons</span></div><div><b>0</b><span>Certificates</span></div></div></div><Link className="row" to="/notifications">Notifications <Icon n="arrow"/></Link><Link className="row" to="/settings">Settings <Icon n="arrow"/></Link><button className="btn o" onClick={()=>{const d=store();d.s=null;save(d);nav('/login')}}>Sign out</button></section>}

const Simple=({title,children})=><section className="sec"><div className="hero inner"><h1>{title}</h1></div><div className="card">{children}</div></section>;
const NotFound=()=> <Simple title="Not found"><p>That page does not exist.</p><Link className="btn" to="/">Go home</Link></Simple>;

function Router(){const{pathname:p}=useLocation();if(p==='/')return <Home/>;if(p==='/courses')return <Courses/>;if(p.startsWith('/courses/'))return <Course/>;if(p==='/learn'||p.startsWith('/learn/'))return <Learn/>;if(p.startsWith('/lesson/'))return <Lesson/>;if(p==='/login')return <Auth/>;if(p==='/signup')return <Auth signup/>;if(p==='/profile')return <Profile/>;if(p==='/notifications')return <Simple title="Notifications"><p className="mu">No new notifications.</p></Simple>;if(p==='/settings')return <Simple title="Settings"><p>Theme preference is available from the top bar.</p></Simple>;if(p==='/support')return <Simple title="Support"><p>Support content can be connected to your production backend here.</p></Simple>;if(p==='/verify')return <Simple title="Verify credential"><input placeholder="Credential code"/></Simple>;return <NotFound/>}
export default function App(){return <Layout><Router/></Layout>}
