import React,{useEffect,useState}from'react';
import{Link,useLocation}from'react-router-dom';

const sections=[
['Curriculum','curriculum'],['Definitions','definitions'],['Assessment','assessment'],['Student terms','terms'],['Refunds','refunds'],['Privacy','privacy'],['Quality standards','qa'],['Independent review','review']
];

export function Handbook(){
 const location=useLocation();
 const routeTab=location.pathname==='/privacy'?'privacy':location.pathname==='/curriculum'?'curriculum':'curriculum';
 const[tab,setTab]=useState(routeTab);
 useEffect(()=>setTab(routeTab),[routeTab]);
 const body={
 curriculum:<><h2>TAMP Curriculum Framework</h2><p>TAMP releases programmes by cohort. A cohort is a defined group of students who begin around the same time and follow a planned academic schedule together. A TAMP cohort can run for approximately <b>one to two months</b>, depending on the programme schedule.</p><p>TAMP is currently offering one technical programme: <b>Data Analysis</b>. The programme is structured as a progressive pathway rather than separate unrelated courses. Students join the cohort currently open for enrollment and progress through the published schedule.</p><h3>Cohort delivery</h3><ul><li>Courses are released for defined cohorts rather than as unrestricted, self-paced starts.</li><li>Each cohort has a planned start period and academic schedule.</li><li>Learning activities, assignments and assessments are released according to the cohort timetable.</li><li>Students normally join the next available cohort when enrollment for a current cohort has closed.</li></ul><div className="policy-grid"><article><span className="pill">PHASE 1</span><h3>Beginner</h3><p>Five-day learning journeys. Each journey combines daily lessons, learning resources, practice, graded assessment and a daily assignment.</p></article><article className="locked-doc"><span className="pill">COMING SOON</span><h3>Intermediate</h3><p>Reserved for the Intermediate curriculum materials. Content will be published after the official TAMP curriculum is prepared.</p></article><article className="locked-doc"><span className="pill">COMING SOON</span><h3>Advanced</h3><p>Reserved for the Advanced curriculum materials. Students progress here only after completing the required earlier phase.</p></article><article className="locked-doc"><span className="pill">COMING SOON</span><h3>Final Project</h3><p>A practical capstone used to demonstrate end-to-end competence and provide the evidence used for final academic records.</p></article></div><h3>Curriculum principles</h3><ul><li>Learning objectives are stated before assessment.</li><li>Learning moves from explanation to practice to evidence.</li><li>Students receive feedback on submitted practical work.</li><li>Assessment records are retained as part of the academic record.</li><li>Course material is reviewed before new cohorts use it.</li></ul></>,
 definitions:<><h2>Academic Definitions</h2><dl className="definition-list"><dt>Course</dt><dd>A complete TAMP programme, such as Data Analysis.</dd><dt>Cohort</dt><dd>A defined group of students who begin a programme around the same time and follow a planned academic schedule together.</dd><dt>Phase</dt><dd>A major stage of a course, such as Beginner, Intermediate or Advanced.</dd><dt>Journey</dt><dd>A five-day learning block inside the current phase.</dd><dt>Lesson</dt><dd>A scheduled learning activity designed around a specific objective.</dd><dt>Practice quiz</dt><dd>Non-graded assessment used for learning and self-checking.</dd><dt>Graded quiz</dt><dd>Formal quiz recorded in the student’s academic results.</dd><dt>Assignment</dt><dd>Practical work submitted by a student for review and scoring.</dd><dt>Practical assessment</dt><dd>An assessment requiring the student to demonstrate a skill by producing or performing something rather than only answering questions.</dd><dt>Final project</dt><dd>The culminating practical assessment for the programme.</dd><dt>Academic transcript</dt><dd>An official TAMP record summarising recorded assessments, scores and completion status.</dd><dt>Certificate</dt><dd>A completion credential issued only when TAMP’s published completion requirements have been satisfied.</dd></dl></>,
 assessment:<><h2>Assessment & grading</h2><p>TAMP assesses both knowledge and practical ability. No single quiz should be treated as the entire measure of a learner.</p><h3>Assessment model</h3><ul><li><b>Practice:</b> low-stakes activities for learning. These do not form the official graded record.</li><li><b>Graded quizzes:</b> formal knowledge checks. Results are released after the configured review period.</li><li><b>Assignments:</b> practical submissions reviewed by TAMP staff and scored out of 100.</li><li><b>Practical/capstone:</b> required where the learning objective is demonstrative or project-based.</li></ul><h3>Completion standard</h3><p>For the current certificate workflow, required graded assessments must meet the published passing threshold of <b>70%</b>, required assignments must be completed/approved, and all required course journeys must be completed. TAMP may require a resubmission where work does not demonstrate the stated objective.</p><h3>Academic integrity</h3><p>Students must submit their own work unless collaboration is explicitly permitted. TAMP may review unusually fast completion, repeated identical work, suspicious activity or other integrity signals. A signal is not automatically treated as a finding of misconduct; the student should be given a fair opportunity to explain or correct the issue.</p><h3>Appeals</h3><p>A student may request a review of a published result through TAMP support. The reviewer should record the reason, evidence considered and final decision.</p></>,
 terms:<><h2>Student terms</h2><p>These starter terms explain how TAMP learning works. They should be reviewed with appropriate legal advice before being treated as a final contractual document.</p><ol><li>Students must provide accurate information during registration and enrollment.</li><li>Account credentials must be kept private. Students are responsible for activity performed through their account.</li><li>Course access is personal and may not be transferred or shared without TAMP approval.</li><li>Students must follow assessment and academic-integrity rules.</li><li>TAMP may temporarily restrict access where necessary for security, abuse prevention, academic-integrity review or serious policy violations.</li><li>Course schedules, assessment dates and learning materials may be updated when necessary. Material changes should be communicated clearly.</li><li>Certificates are not guaranteed merely by enrollment or payment. They are issued after the published completion requirements are satisfied.</li><li>Nothing in these terms removes rights that cannot lawfully be excluded under applicable Nigerian law.</li></ol></>,
 refunds:<><h2>Refund Policy</h2><p>TAMP aims to keep its starter refund process simple and fair. This policy is subject to applicable consumer-protection law.</p><div className="policy-grid"><article><h3>Unused enrollment</h3><p>If an enrollment key has not been redeemed and the student has not accessed the course, request a refund through the official TAMP support channel. The payment record and key status will be checked before approval.</p></article><article><h3>Duplicate payment</h3><p>Verified duplicate payments should be refunded or otherwise resolved promptly after the duplicate transaction is confirmed.</p></article><article><h3>Service failure</h3><p>If TAMP cannot provide the purchased course access because of a material service failure within TAMP’s control, support will investigate and may provide access, replacement enrollment or an appropriate refund.</p></article><article><h3>After access</h3><p>Once a single-use enrollment key has been redeemed and course access has been materially used, refunds are generally not available except where required by law or where TAMP has failed to deliver the purchased service.</p></article></div><p>Refund requests should include the student email, payment reference, date and reason. TAMP should keep a record of the decision.</p></>,
 privacy:<><h2>Data Protection & Privacy</h2><p>TAMP collects only the information reasonably required to operate student accounts, enrollment, learning, assessment, certificates, support and security. TAMP should process personal data fairly, lawfully and transparently, keep it accurate, limit collection to what is necessary, retain it only as needed, and protect it against unauthorised access or loss. These principles align with the Nigeria Data Protection Act framework described by the Nigeria Data Protection Commission.</p><h3>Information we may hold</h3><ul><li>Account and contact information.</li><li>Enrollment and education information supplied by the student.</li><li>Course progress, quiz attempts, grades and assignment submissions.</li><li>Certificate and verification records.</li><li>Security, device and service information required to operate and protect the platform.</li></ul><h3>Why we use it</h3><p>To provide the course, administer assessments, issue credentials, communicate important course events, maintain security, improve TAMP and meet applicable legal or operational obligations.</p><h3>Student rights</h3><p>Students should be able to request information about their personal data, request correction of inaccurate information and exercise other rights available under applicable data-protection law. TAMP should maintain a clear privacy contact and a process for handling such requests. The NDPC identifies rights including access, rectification, objection, portability, erasure and complaint mechanisms.</p><h3>Privacy by design</h3><p>TAMP should avoid exposing private student records publicly. Certificate verification should expose only the minimum information necessary to verify authenticity.</p></>,
 qa:<><h2>Quality standards</h2><p>TAMP can start with a lightweight internal quality system instead of building a large bureaucracy.</p><div className="qa-list"><div><b>Before a cohort</b><span>Review curriculum, links, videos, assignments, quiz answers, grading rules and access dates.</span></div><div><b>During a cohort</b><span>Monitor broken lessons, completion anomalies, complaints, grading turnaround and student feedback.</span></div><div><b>After a cohort</b><span>Review results, difficult questions, assignment quality, drop-off points and student comments.</span></div><div><b>Version control</b><span>Record curriculum version, policy version and material changes so the academic team knows which version a student studied.</span></div><div><b>Assessment moderation</b><span>Periodically sample graded assignments and quizzes to check that marking is consistent with the rubric.</span></div></div><p>NBTE publishes quality-assurance instruments and guidance for TVET institutions, including quality assurance management systems and technology-enabled QA resources. These are useful benchmarks for TAMP’s future maturity, but TAMP should not claim NBTE approval merely because it follows similar practices.</p></>,
 review:<><h2>Independent review</h2><p>When TAMP grows, invite an independent practitioner or educator to review the programme before calling the curriculum industry-validated.</p><h3>Starter review process</h3><ol><li>Choose a reviewer with relevant Data Analysis/education experience and no grading conflict.</li><li>Give the reviewer the curriculum, learning outcomes, assessments and grading rubric.</li><li>Ask for written findings on relevance, difficulty, practical coverage, assessment validity and clarity.</li><li>Record recommendations and assign an owner/date for each improvement.</li><li>Publish a simple “reviewed on” record internally and retain the report.</li></ol><p>External review is an internal quality measure, not accreditation. Formal recognition requires the applicable regulator and approval process. NBTE’s published materials describe approval/accreditation as a structured quality-assurance process.</p></>
 }[tab];
 return <section className="sec handbook"><div className="hero inner"><p className="eyebrow">TAMP · ACADEMIC HANDBOOK</p><h1>Your TAMP guide</h1><p className="lead">A clear guide to how learning, assessment, records and student support work at TAMP.</p></div><div className="policy-tabs">{sections.map(([x,k])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{x}</button>)}</div><article className="card policy-doc">{body}<p className="policy-version">TAMP starter framework · Version 1.0 · Review before each major cohort</p></article></section>
}

export function Transcript({user,profile}){
 const[grades,setGrades]=useState([]),[submissions,setSubmissions]=useState([]),[summary,setSummary]=useState(null),[busy,setBusy]=useState(true);
 useEffect(()=>{Promise.all([supabase.rpc('get_my_grades'),supabase.from('submissions').select('id,status,submitted_at,assessment_results(score,feedback,created_at),assignments(title,week_number,day_number)').eq('student_id',user.id).order('submitted_at',{ascending:false})]).then(([g,sub])=>{setGrades(g.data||[]);setSubmissions(sub.data||[]);return supabase.rpc('get_my_grade_summary')}).then(s=>setSummary(s.data?.[0]||s.data||null)).finally(()=>setBusy(false))},[]);
 return <section className="sec transcript-page"><div className="hero inner"><p className="eyebrow">TAMP · ACADEMIC RECORD</p><h1>Academic transcript</h1><p className="lead">A student-facing record of your released graded quizzes and reviewed practical assignments.</p></div><div className="card transcript-head"><div><span className="mu">Student</span><h2>{profile?.full_name||'Student'}</h2><p>{profile?.student_id||'—'} · {user.email}</p></div><div className="transcript-stat"><b>{Number(summary?.average_percent||0).toFixed(2)}%</b><span>overall graded average</span></div></div>{busy?<div className="card">Preparing your academic record…</div>:<div className="card table-wrap"><table><thead><tr><th>Assessment</th><th>Journey</th><th>Score</th><th>Released</th></tr></thead><tbody>{grades.map(g=><tr key={'q-'+g.attempt_id}><td>{g.quiz_title}</td><td>Week {g.journey_number||'—'} · Day {g.day_number||'—'}</td><td>{Number(g.score_percent||0).toFixed(2)}%</td><td>{g.released_at?new Date(g.released_at).toLocaleDateString('en-NG'):'—'}</td></tr>)}{submissions.map(x=>{const r=Array.isArray(x.assessment_results)?x.assessment_results[0]:x.assessment_results;return <tr key={'a-'+x.id}><td>{x.assignments?.title||'Assignment'}</td><td>Week {x.assignments?.week_number||'—'} · Day {x.assignments?.day_number||'—'}</td><td>{r?.score==null?'Pending':Number(r.score).toFixed(2)+'%'}</td><td>{r?.created_at?new Date(r.created_at).toLocaleDateString('en-NG'):'—'}</td></tr>})}</tbody></table>{!grades.length&&<p className="mu">No released graded assessments yet.</p>}</div>}</section>
}
