import{useEffect}from'react';

const SITE='https://r2-kryonara1.vercel.app';
const base={name:'TAMP · Technical Campus',description:'TAMP is a cohort-based technical learning platform offering structured, practical learning with lessons, assignments, assessments, feedback and verifiable academic records.',image:SITE+'/og-image.png'};
const pages={
 '/':{title:'TAMP · Technical Campus | Cohort-Based Technical Learning',description:'Learn practical technical skills through structured TAMP cohorts, daily learning, practical assignments, assessment, feedback and verifiable achievement.'},
 '/courses':{title:'Data Analysis Programme | TAMP · Technical Campus',description:'Explore TAMP’s Data Analysis programme, cohort schedule, Beginner phase, five-day learning journeys, assessments, practical assignments and certificate pathway.'},
 '/courses/da':{title:'Data Analysis Course | Beginner to Advanced Pathway | TAMP',description:'Join the TAMP Data Analysis programme. Learn through cohort-based five-day journeys, practice, graded assessments, practical assignments and a final project.'},
 '/handbook':{title:'Academic Handbook | TAMP · Technical Campus',description:'Read TAMP’s curriculum, assessment, student terms, refund policy, privacy principles, quality standards and independent review framework.'},
 '/curriculum':{title:'Curriculum | TAMP Data Analysis Programme',description:'Understand the TAMP Data Analysis curriculum: Beginner five-day journeys, future Intermediate and Advanced phases, final project and certificate requirements.'},
 '/privacy':{title:'Privacy & Data Protection | TAMP · Technical Campus',description:'Learn how TAMP approaches student information, privacy, data protection, security, academic records and certificate verification.'},
 '/verify':{title:'Certificate Verification | TAMP · Technical Campus',description:'Verify a TAMP certificate using its certificate ID and confirm the authenticity of a TAMP academic credential.'},
 '/students':{title:'Student Voices | TAMP · Technical Campus',description:'Read approved student feedback about learning experiences at TAMP.'},
 '/payment':{title:'Online Enrollment | TAMP · Technical Campus',description:'Learn how to pay the TAMP Data Analysis course fee and continue with student enrollment.'},
 '/pay':{title:'Online Enrollment | TAMP · Technical Campus',description:'TAMP online enrollment and course payment information.'}
};
const courseLd={ '@context':'https://schema.org', '@type':'Course',name:'Data Analysis',description:'A practical, cohort-based Data Analysis programme beginning with a Beginner phase of five-day learning journeys and progressing toward Intermediate, Advanced and a final project.',provider:{'@type':'EducationalOrganization',name:'TAMP · Technical Campus',url:SITE},courseMode:'online',inLanguage:'en',offers:{'@type':'Offer',price:'2000',priceCurrency:'NGN',url:SITE+'/payment'},hasCourseInstance:{'@type':'CourseInstance',courseMode:'online',startDate:'2026-10-21',url:SITE+'/courses/da'}};
export default function Seo({path='/'}){useEffect(()=>{const p=pages[path]||pages['/'];document.title=p.title;const set=(name,content)=>{let el=document.head.querySelector('meta[name="'+name+'"]');if(!el){el=document.createElement('meta');el.name=name;document.head.appendChild(el)}el.content=content};set('description',p.description);set('robots','index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1');set('theme-color','#09090a');let link=document.head.querySelector('link[rel="canonical"]');if(!link){link=document.createElement('link');link.rel='canonical';document.head.appendChild(link)}link.href=SITE+(path==='/'?'':path);set('og:title',p.title);set('og:description',p.description);set('og:type',path==='/courses/da'?'article':'website');set('og:url',SITE+(path==='/'?'':path));set('og:site_name','TAMP · Technical Campus');set('twitter:card','summary_large_image');set('twitter:title',p.title);set('twitter:description',p.description);let old=document.head.querySelector('script[data-tamp-schema]');if(old)old.remove();const s=document.createElement('script');s.type='application/ld+json';s.dataset.tampSchema='true';s.textContent=JSON.stringify(path==='/courses/da'?courseLd:{'@context':'https://schema.org','@type':'EducationalOrganization',name:base.name,url:SITE,description:base.description});document.head.appendChild(s)},[path]);return null}
