-- R2 / Reelhouse production foundation
-- Email/password Auth only. Keep Google/OAuth providers disabled unless explicitly added later.

create extension if not exists pgcrypto;

-- Remove an unrelated/unsafe public helper if it exists.
revoke execute on function public.rls_auto_enable() from public, anon, authenticated;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  avatar_url text,
  preferences jsonb not null default '{}'::jsonb,
  taste_profile jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_devices (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  installation_id text not null,
  device_name text not null default 'Android device',
  manufacturer text,
  model text,
  android_version text,
  app_version text,
  platform text not null default 'android',
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  revoked_at timestamptz,
  unique(user_id, installation_id)
);

create index if not exists user_devices_user_idx on public.user_devices(user_id);
create index if not exists user_devices_last_seen_idx on public.user_devices(user_id, last_seen_at desc);

create table if not exists public.preference_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  movie_id bigint,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists preference_events_user_time_idx on public.preference_events(user_id, created_at desc);

create table if not exists public.followed_people (
  user_id uuid not null references auth.users(id) on delete cascade,
  person_id bigint not null,
  person_name text,
  created_at timestamptz not null default now(),
  primary key(user_id, person_id)
);

create table if not exists public.watch_state (
  user_id uuid not null references auth.users(id) on delete cascade,
  movie_id bigint not null,
  progress_seconds integer not null default 0,
  duration_seconds integer not null default 0,
  completed boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key(user_id, movie_id)
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

create or replace function public.enforce_three_devices()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  active_count integer;
begin
  if new.revoked_at is not null then
    return new;
  end if;

  select count(*) into active_count
  from public.user_devices
  where user_id = new.user_id
    and revoked_at is null
    and id <> new.id;

  if active_count >= 3 then
    raise exception 'DEVICE_LIMIT_REACHED';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_three_devices_insert_trigger on public.user_devices;
create trigger enforce_three_devices_insert_trigger
before insert on public.user_devices
for each row execute function public.enforce_three_devices();

drop trigger if exists enforce_three_devices_update_trigger on public.user_devices;
create trigger enforce_three_devices_update_trigger
before update of user_id, revoked_at on public.user_devices
for each row execute function public.enforce_three_devices();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles(id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email,''), '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.user_devices enable row level security;
alter table public.preference_events enable row level security;
alter table public.followed_people enable row level security;
alter table public.watch_state enable row level security;

drop policy if exists profiles_self on public.profiles;
create policy profiles_self on public.profiles
for all to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists devices_self on public.user_devices;
create policy devices_self on public.user_devices
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists preference_events_self on public.preference_events;
create policy preference_events_self on public.preference_events
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists followed_people_self on public.followed_people;
create policy followed_people_self on public.followed_people
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

drop policy if exists watch_state_self on public.watch_state;
create policy watch_state_self on public.watch_state
for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

revoke all on table public.profiles, public.user_devices, public.preference_events, public.followed_people, public.watch_state from anon;
grant select, insert, update, delete on public.profiles, public.user_devices, public.preference_events, public.followed_people, public.watch_state to authenticated;

revoke execute on function public.touch_updated_at() from public, anon, authenticated;
revoke execute on function public.enforce_three_devices() from public, anon, authenticated;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
